[package]
name = "tokio-native-tls"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag.
version = "0.3.1"
edition = "2018"
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"
repository = "https://github.com/tokio-rs/tls"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tokio-native-tls"
description = """
An implementation of TLS/SSL streams for Tokio using native-tls giving an implementation of TLS
for nonblocking I/O streams.
"""
categories = ["asynchronous", "network-programming"]

[dependencies]
native-tls = { git = "https://github.com/paranoikcodit/rust-native-tls/" }
tokio = "1.0"

[features]
vendored = ["native-tls/vendored"]
boring = ["native-tls/boring"]

[dev-dependencies]
tokio = { version = "1.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "io-util",
    "net",
] }
cfg-if = "1.0"
env_logger = { version = "0.10", default-features = false }
futures = { version = "0.3.0", features = ["async-await"] }

tempfile = "3.1"
lazy_static = "1.4.0"

[package.metadata.docs.rs]
all-features = true
